// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVRY4wfhFV17u1IvWVgYsS73gcIdJjw3A',
    appId: '1:12293634670:web:d433c79342b4029f7e847f',
    messagingSenderId: '12293634670',
    projectId: 'securiteinfo-cdf92',
    authDomain: 'securiteinfo-cdf92.firebaseapp.com',
    storageBucket: 'securiteinfo-cdf92.appspot.com',
    measurementId: 'G-08FSCD35S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3WAuNzLfr8RwemmNVgQI1Y8nwX3LwihU',
    appId: '1:12293634670:android:72724041c9f418c67e847f',
    messagingSenderId: '12293634670',
    projectId: 'securiteinfo-cdf92',
    storageBucket: 'securiteinfo-cdf92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnxqjKr8_Zwmfwv7SM7gYvsZwcJBCBoCM',
    appId: '1:12293634670:ios:49b2d50ad89bda417e847f',
    messagingSenderId: '12293634670',
    projectId: 'securiteinfo-cdf92',
    storageBucket: 'securiteinfo-cdf92.appspot.com',
    iosBundleId: 'com.example.testSecInf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnxqjKr8_Zwmfwv7SM7gYvsZwcJBCBoCM',
    appId: '1:12293634670:ios:9af2a3f0675aaff57e847f',
    messagingSenderId: '12293634670',
    projectId: 'securiteinfo-cdf92',
    storageBucket: 'securiteinfo-cdf92.appspot.com',
    iosBundleId: 'com.example.testSecInf.RunnerTests',
  );
}
